oauth2:
  providers:
    google:
      client_id: your_client_id
      client_secret: your_client_secret
      redirect_uri: http://localhost:8080/auth/google/callback
      scopes:
        - https://www.googleapis.com/auth/userinfo.email
        - https://www.googleapis.com/auth/userinfo.profile
        - openid